// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpc-NIkGX94cvGAkpp7H_hg4dYYHLv6M',
    appId: '1:1026956907987:web:eda281259a993296cc8b26',
    messagingSenderId: '1026956907987',
    projectId: 'flutter-noted-app',
    authDomain: 'flutter-noted-app.firebaseapp.com',
    storageBucket: 'flutter-noted-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNRFV4mf3Y9VSCto9hNdOdVQzinTorXo',
    appId: '1:1026956907987:android:299db8848087efd1cc8b26',
    messagingSenderId: '1026956907987',
    projectId: 'flutter-noted-app',
    storageBucket: 'flutter-noted-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLxeiVBfsVOhhDR5FOFJz9INK49oZfK-I',
    appId: '1:1026956907987:ios:e8378275212bb146cc8b26',
    messagingSenderId: '1026956907987',
    projectId: 'flutter-noted-app',
    storageBucket: 'flutter-noted-app.appspot.com',
    iosBundleId: 'geek.wys.noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLxeiVBfsVOhhDR5FOFJz9INK49oZfK-I',
    appId: '1:1026956907987:ios:38c56339cfa2c2a9cc8b26',
    messagingSenderId: '1026956907987',
    projectId: 'flutter-noted-app',
    storageBucket: 'flutter-noted-app.appspot.com',
    iosBundleId: 'geek.wys.noted.RunnerTests',
  );
}
